name: stats
channels:
  - defaults
dependencies:
  - tensorflow==2.8.0
  - keras == 2.8.0
  - scipy
  - scikit-learn==0.20.2
  - pandas==1.4.1
  - numpy==1.21.5
  - plotly
  - matplotlib
  - pillow
  - librosa
  - joblib

